kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: mahiketh/s-app:v1
        env:
        - name: APP
          value: app-1