kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: mahiketh/app-2:v1
---
kind: Service
apiVersion: v1
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
  - name: app2-port
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app2
  annotations:
    #kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:339712874850:certificate/d2c68ee8-1a15-46de-94f2-6a39f454dbfb
    alb.ingress.kubernetes.io/listen-ports: '[ {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/group.name: expense
spec:
  ingressClassName: alb
  rules:
  - host: "app2.mahdo.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80