kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: mahiketh/app-1:v1
---
kind: Service
apiVersion: v1
metadata:
  name: app-1
spec:
  selector:
    name: app-1
  ports:
  - name: app-1-port
    protocol: TCP
    port: 80
    targetPort: 80